name: First Workflow

on: push
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a Message
        run: echo "Hello From My First Github Action"

      - name: Check Linting
        run: echo "Check linting first"
        
    
